# Generated by Django 5.1.7 on 2025-03-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicians',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patients',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
